package com.kyant.pixelmusic.api.album

data class Song(
    val rtUrls: List<Any>? = listOf(),
    val ar: List<Ar>? = listOf(),
    val al: Al? = Al(),
    val st: Int? = 0,
    val noCopyrightRcmd: Any? = Any(),
    val a: Any? = Any(),
    val m: M? = M(),
    val pst: Int? = 0,
    val t: Int? = 0,
    val alia: List<String>? = listOf(),
    val pop: Int? = 0,
    val rt: String? = "",
    val mst: Int? = 0,
    val cp: Int? = 0,
    val cf: String? = "",
    val dt: Int? = 0,
    val h: H? = H(),
    val l: L? = L(),
    val rtype: Int? = 0,
    val rurl: Any? = Any(),
    val crbt: Any? = Any(),
    val rtUrl: Any? = Any(),
    val ftype: Int? = 0,
    val v: Int? = 0,
    val djId: Int? = 0,
    val no: Int? = 0,
    val fee: Int? = 0,
    val mv: Int? = 0,
    val cd: String? = "",
    val name: String? = "",
    val id: Int? = 0,
    val privilege: Privilege? = Privilege()
)