package com.kyant.pixelmusic.api.playlist

data class Playlist(
    val subscribers: List<Subscriber>? = listOf(),
    val subscribed: Boolean? = false,
    val creator: Creator? = Creator(),
    val tracks: List<Track>? = listOf(),
    val videoIds: Any? = Any(),
    val videos: Any? = Any(),
    val trackIds: List<TrackId>? = listOf(),
    val updateFrequency: Any? = Any(),
    val backgroundCoverId: Int? = 0,
    val backgroundCoverUrl: Any? = Any(),
    val titleImage: Int? = 0,
    val titleImageUrl: Any? = Any(),
    val englishTitle: Any? = Any(),
    val opRecommend: Boolean? = false,
    val adType: Int? = 0,
    val trackNumberUpdateTime: Long? = 0,
    val userId: Int? = 0,
    val createTime: Long? = 0,
    val highQuality: Boolean? = false,
    val updateTime: Long? = 0,
    val newImported: Boolean? = false,
    val coverImgId: Long? = 0,
    val trackCount: Int? = 0,
    val coverImgUrl: String? = "",
    val specialType: Int? = 0,
    val trackUpdateTime: Long? = 0,
    val commentThreadId: String? = "",
    val privacy: Int? = 0,
    val playCount: Long? = 0,
    val subscribedCount: Int? = 0,
    val cloudTrackCount: Int? = 0,
    val ordered: Boolean? = false,
    val tags: List<String>? = listOf(),
    val description: String? = "",
    val status: Int? = 0,
    val name: String? = "",
    val id: Long? = 0,
    val shareCount: Int? = 0,
    val coverImgId_str: String? = "",
    val commentCount: Int? = 0
)